### PR TITLE
added "-and-version-information" to generic url

### PR DESCRIPTION
**Pull request by KatherineTomkins**

### CODE REVIEW

**Comment by tommyb82** [comment]
The example notifications have actually changed in a couple of other ways - addition of the `created_time` attribute (directly relevant to versioning) and also @robert-lil 's unique diagnostic stuff.. worth including those bits as appropriate?

**Comment by KatherineTomkins** [comment]
Sure - as part of this ticket?

**Comment by KatherineTomkins** [comment]
I have added the created_time attribute - but will leave the unique diagnostic name for another ticket.

**Comment by robert-lil** [comment]
Would probably be worth having "updated the example code" in the definition of done for each ticket if applicable.

**Review by tommyb82 — APPROVED** [review]

**Review by adrianmilne — APPROVED** [review]

**Review by wdmearns — APPROVED** [review]

**Pull request merged**
